### ISSUE TITLE
Connecting to IOS and NXOS devices using unicon enters configuration mode

### ISSUE THREAD

**Issue by jesse-mcgraw** [CiscoTestAutomation/genielibs#12]
When initially connecting to a device using Unicon configuration mode is entered in order to change terminal parameters and this is reflected in the syslog

Ideally, connecting to a device and learning information should be a read-only operation (ie to avoid the issue where entering configuration mode outside of maintenance window in a production environment is not allowed)

Is there a way to disable this behavior or can the desired parameters be set from outside of configuration mode instead?

### eg The log from connecting to an NXOS switch: 

```
  [2019-06-11 14:03:23,252] +++ lab_2960_s: config +++
  config term
  Enter configuration commands, one per line.  End with CNTL/Z.
  lab_2960_s(config)#no logging console
  lab_2960_s(config)#line console 0
  lab_2960_s(config-line)#exec-timeout 0
  lab_2960_s(config-line)#end
  lab_2960_s#
```

### and the corresponding syslog entries
```
  lab_2960_s#show log
  Jun 11 14:14:27.577: %SYS-5-CONFIG_I: Configured from console by admin on vty0 
  (10.1.1.1)
```

### testbed parameters used for connection

```
 connections:
      defaults:
        class: 'unicon.Unicon'
      vty:
        protocol: ssh
        ip: lab_2960_s
```

**Comment by karmoham** [comment]
Hi Jesse,

You can disable the initialization commands through the testbed yaml file by setting **init_exec_commands** and **init_config_commands** as empty lists.

Make sure you have the latest **Unicon** version in your environment;

_pip install unicon_ 

And here how to set it up in your yaml files;

```
devices:
  nx-osv-1:
      type: 'router'
      os: 'nxos'
      alias: 'uut'
      tacacs:
          login_prompt: "login:"
          password_prompt: "Password:"
          username: "admin"
      passwords:
          tacacs: admin
          enable: admin
          line: admin
      connections:
          defaults:
            class: 'unicon.Unicon'
          cli:
              protocol: telnet
              init_exec_commands: []
              init_config_commands: []
              ip: "1.1.1.1"
              port: 12345
```

Thanks,
Karim
