### ISSUE TITLE
Genie CLI makes config changes to line console and line default on IOSXR

### ISSUE THREAD

**Issue by pwoconnor** [CiscoTestAutomation/genielibs#8]
Everytime Genie connects to a IOSXR device it makes configuration changes the line console and line default. Is there a way to turn that feature off?

```
RP/0/RSP0/CPU0:LAB-9010#
[2019-04-19 22:07:20,843] +++ initializing handle +++
[2019-04-19 22:07:20,844] +++ LAB-9010: executing command 'terminal length 0' +++
terminal length 0
Fri Apr 19 22:07:21.002 CDT
RP/0/RSP0/CPU0:LAB-9010#
[2019-04-19 22:07:21,093] +++ LAB-9010: executing command 'terminal width 0' +++
terminal width 0
Fri Apr 19 22:07:21.236 CDT
RP/0/RSP0/CPU0:LAB-9010#
[2019-04-19 22:07:21,312] +++ LAB-9010: config +++
configure terminal
Fri Apr 19 22:07:21.458 CDT
RP/0/RSP0/CPU0:LAB-9010(config)#no logging console
RP/0/RSP0/CPU0:LAB-9010(config)#line console
RP/0/RSP0/CPU0:LAB-9010(config-line)#exec-timeout 0 0
RP/0/RSP0/CPU0:LAB-9010(config-line)#absolute-timeout 0
RP/0/RSP0/CPU0:LAB-9010(config-line)#session-timeout 0
RP/0/RSP0/CPU0:LAB-9010(config-line)#line default
RP/0/RSP0/CPU0:LAB-9010(config-line)#exec-timeout 0 0
RP/0/RSP0/CPU0:LAB-9010(config-line)#absolute-timeout 0
RP/0/RSP0/CPU0:LAB-9010(config-line)#session-timeout 0
RP/0/RSP0/CPU0:LAB-9010(config-line)#commit

Fri Apr 19 22:07:23.373 CDT
RP/0/RSP0/CPU0:LAB-9010(config-line)#end
RP/0/RSP0/CPU0:LAB-9010#
```

**Comment by jeaubin** [comment]
Yes you can deactivate them

https://pubhub.devnetcloud.com/media/pyats-packages/docs/unicon/user_guide/connection.html

device.connect(init_exec_commands=[], init_config_commands=[])

These will remove all initial command send when connecting.

**Comment by pwoconnor** [comment]
Thanks jeaubin, but that is for creating pyats connections. My question is specifically about GenieCLI which works off of a yaml file with connection parameters. Now I would assume that I need what you linked, but I am not sure where they would go in the testbed yaml file.

**Comment by jeaubin** [comment]
I see; 

I'll need to do some test on my side first to make sure it works as expected. I'll be back in the office on Tuesday.

**Comment by jeaubin** [comment]
We will release a new version of Unicon to allows this.  The planned released is for next Tuesday.

Thanks for reporting it!

**Comment by pwoconnor** [comment]
Any news on the release for Unicon to alleviate this issue?

**Comment by karmoham** [comment]
Hi Patrick,

We released **unicon** version [19.4.0](https://pypi.org/project/unicon/) so please upgrade the package and let us know if it solves your issues.

_pip install --upgrade unicon_

Thanks,
Karim

**Comment by pwoconnor** [comment]
New update does the same thing I reported, when running genie learn, When the session is connected. The program goes straight into config mode and commits various timeout values for line console and line default.

**Comment by karmoham** [comment]
@jeaubin to comment

**Comment by jeaubin** [comment]
Hi @pwoconnor , Sorry for the delay, I've done the enhancement, however, there has been some issue with the release. We are currently in Business trip;  I'll publish it once we come back,  early next week.

**Comment by pwoconnor** [comment]
Ok thanks for the update!

**Comment by pwoconnor** [comment]
Hi @jeaubin Do you still plan on releasing this week?

**Comment by jeaubin** [comment]
Hi @pwoconnor ,   it is now released as a beta package!

Sorry for the delay, Here how to get the latest version

pip install unicon --upgrade --pre

(--pre for beta packages)


And here how to set it up in your yaml files

```
devices:
  nx-osv-1:
      type: 'router'
      os: 'nxos'
      alias: 'uut'
      tacacs:
          login_prompt: "login:"
          password_prompt: "Password:"
          username: "admin"
      passwords:
          tacacs: admin
          enable: admin
          line: admin
      connections:
          defaults:
            class: 'unicon.Unicon'
          cli:
              protocol: telnet
              init_exec_commands: []
              init_config_commands: []
              ip: "1.1.1.1"
              port: 17036
```
